### ISSUE TITLE
FTP error: 550 Size not allowed in ASCII mode. Fix proposed

### ISSUE THREAD

**Issue by VladimirIvonin** [mattkjames7/kpindex#2]
Hello! Function `UpdateLocalData` caused error `550 Size not allowed in ASCII mode` and it's impossible to download data from GFZ German Research Centre for Geosciences. This error is from `ftplib` module caused by following code string of the `_GetCallback` function in file `kpindex/DownloadFTPFile.py`:
```Python
size = ftp.size(fname)
```
It can be fixed by adding the following code string before this line:
```Python
ftp.voidcmd('TYPE I')
```

**Comment by mattkjames7** [comment]
Good spot, thanks for the fix, it is greatly appreciated! I'll post an update shortly...
